import Footer from '@/components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import Headline from '@/components/Headline'
import Navbar from '@/components/Navbar'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div>
          <Headline/>
          <Navbar/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  )
}
